/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appHistoryRouteRouteImport } from './routes/(app)/history/route'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLogoutIndexRouteImport } from './routes/_auth/logout/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as appPrivacyPolicyIndexRouteImport } from './routes/(app)/privacy-policy/index'
import { Route as appPricingIndexRouteImport } from './routes/(app)/pricing/index'
import { Route as appCheckoutIndexRouteImport } from './routes/(app)/checkout/index'
import { Route as appAccountIndexRouteImport } from './routes/(app)/account/index'
import { Route as AuthResetPasswordIdRouteImport } from './routes/_auth/reset-password/$id'
import { Route as appVerifyTokenRouteImport } from './routes/(app)/verify/$token'
import { Route as appAnalyseIdRouteImport } from './routes/(app)/analyse/$id'
import { Route as appCheckoutSuccessIndexRouteImport } from './routes/(app)/checkout/success/index'
import { Route as appCheckoutCancelIndexRouteImport } from './routes/(app)/checkout/cancel/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appHistoryRouteRoute = appHistoryRouteRouteImport.update({
  id: '/(app)/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLogoutIndexRoute = AuthLogoutIndexRouteImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const appPrivacyPolicyIndexRoute = appPrivacyPolicyIndexRouteImport.update({
  id: '/(app)/privacy-policy/',
  path: '/privacy-policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const appPricingIndexRoute = appPricingIndexRouteImport.update({
  id: '/(app)/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const appCheckoutIndexRoute = appCheckoutIndexRouteImport.update({
  id: '/(app)/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const appAccountIndexRoute = appAccountIndexRouteImport.update({
  id: '/(app)/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIdRoute = AuthResetPasswordIdRouteImport.update({
  id: '/reset-password/$id',
  path: '/reset-password/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const appVerifyTokenRoute = appVerifyTokenRouteImport.update({
  id: '/(app)/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const appAnalyseIdRoute = appAnalyseIdRouteImport.update({
  id: '/(app)/analyse/$id',
  path: '/analyse/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const appCheckoutSuccessIndexRoute = appCheckoutSuccessIndexRouteImport.update({
  id: '/(app)/checkout/success/',
  path: '/checkout/success/',
  getParentRoute: () => rootRouteImport,
} as any)
const appCheckoutCancelIndexRoute = appCheckoutCancelIndexRouteImport.update({
  id: '/(app)/checkout/cancel/',
  path: '/checkout/cancel/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof appHistoryRouteRoute
  '/analyse/$id': typeof appAnalyseIdRoute
  '/verify/$token': typeof appVerifyTokenRoute
  '/reset-password/$id': typeof AuthResetPasswordIdRoute
  '/account/': typeof appAccountIndexRoute
  '/checkout/': typeof appCheckoutIndexRoute
  '/pricing/': typeof appPricingIndexRoute
  '/privacy-policy/': typeof appPrivacyPolicyIndexRoute
  '/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/logout/': typeof AuthLogoutIndexRoute
  '/register/': typeof AuthRegisterIndexRoute
  '/checkout/cancel/': typeof appCheckoutCancelIndexRoute
  '/checkout/success/': typeof appCheckoutSuccessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof appHistoryRouteRoute
  '/analyse/$id': typeof appAnalyseIdRoute
  '/verify/$token': typeof appVerifyTokenRoute
  '/reset-password/$id': typeof AuthResetPasswordIdRoute
  '/account': typeof appAccountIndexRoute
  '/checkout': typeof appCheckoutIndexRoute
  '/pricing': typeof appPricingIndexRoute
  '/privacy-policy': typeof appPrivacyPolicyIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/logout': typeof AuthLogoutIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/checkout/cancel': typeof appCheckoutCancelIndexRoute
  '/checkout/success': typeof appCheckoutSuccessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/(app)/history': typeof appHistoryRouteRoute
  '/(app)/analyse/$id': typeof appAnalyseIdRoute
  '/(app)/verify/$token': typeof appVerifyTokenRoute
  '/_auth/reset-password/$id': typeof AuthResetPasswordIdRoute
  '/(app)/account/': typeof appAccountIndexRoute
  '/(app)/checkout/': typeof appCheckoutIndexRoute
  '/(app)/pricing/': typeof appPricingIndexRoute
  '/(app)/privacy-policy/': typeof appPrivacyPolicyIndexRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/logout/': typeof AuthLogoutIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/(app)/checkout/cancel/': typeof appCheckoutCancelIndexRoute
  '/(app)/checkout/success/': typeof appCheckoutSuccessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/analyse/$id'
    | '/verify/$token'
    | '/reset-password/$id'
    | '/account/'
    | '/checkout/'
    | '/pricing/'
    | '/privacy-policy/'
    | '/forgot-password/'
    | '/login/'
    | '/logout/'
    | '/register/'
    | '/checkout/cancel/'
    | '/checkout/success/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/analyse/$id'
    | '/verify/$token'
    | '/reset-password/$id'
    | '/account'
    | '/checkout'
    | '/pricing'
    | '/privacy-policy'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/register'
    | '/checkout/cancel'
    | '/checkout/success'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/(app)/history'
    | '/(app)/analyse/$id'
    | '/(app)/verify/$token'
    | '/_auth/reset-password/$id'
    | '/(app)/account/'
    | '/(app)/checkout/'
    | '/(app)/pricing/'
    | '/(app)/privacy-policy/'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/_auth/logout/'
    | '/_auth/register/'
    | '/(app)/checkout/cancel/'
    | '/(app)/checkout/success/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  appHistoryRouteRoute: typeof appHistoryRouteRoute
  appAnalyseIdRoute: typeof appAnalyseIdRoute
  appVerifyTokenRoute: typeof appVerifyTokenRoute
  appAccountIndexRoute: typeof appAccountIndexRoute
  appCheckoutIndexRoute: typeof appCheckoutIndexRoute
  appPricingIndexRoute: typeof appPricingIndexRoute
  appPrivacyPolicyIndexRoute: typeof appPrivacyPolicyIndexRoute
  appCheckoutCancelIndexRoute: typeof appCheckoutCancelIndexRoute
  appCheckoutSuccessIndexRoute: typeof appCheckoutSuccessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/history': {
      id: '/(app)/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof appHistoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/logout/': {
      id: '/_auth/logout/'
      path: '/logout'
      fullPath: '/logout/'
      preLoaderRoute: typeof AuthLogoutIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(app)/privacy-policy/': {
      id: '/(app)/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof appPrivacyPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/pricing/': {
      id: '/(app)/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof appPricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/checkout/': {
      id: '/(app)/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof appCheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/account/': {
      id: '/(app)/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof appAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password/$id': {
      id: '/_auth/reset-password/$id'
      path: '/reset-password/$id'
      fullPath: '/reset-password/$id'
      preLoaderRoute: typeof AuthResetPasswordIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(app)/verify/$token': {
      id: '/(app)/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof appVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/analyse/$id': {
      id: '/(app)/analyse/$id'
      path: '/analyse/$id'
      fullPath: '/analyse/$id'
      preLoaderRoute: typeof appAnalyseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/checkout/success/': {
      id: '/(app)/checkout/success/'
      path: '/checkout/success'
      fullPath: '/checkout/success/'
      preLoaderRoute: typeof appCheckoutSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/checkout/cancel/': {
      id: '/(app)/checkout/cancel/'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel/'
      preLoaderRoute: typeof appCheckoutCancelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthResetPasswordIdRoute: typeof AuthResetPasswordIdRoute
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthLogoutIndexRoute: typeof AuthLogoutIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthResetPasswordIdRoute: AuthResetPasswordIdRoute,
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthLogoutIndexRoute: AuthLogoutIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  appHistoryRouteRoute: appHistoryRouteRoute,
  appAnalyseIdRoute: appAnalyseIdRoute,
  appVerifyTokenRoute: appVerifyTokenRoute,
  appAccountIndexRoute: appAccountIndexRoute,
  appCheckoutIndexRoute: appCheckoutIndexRoute,
  appPricingIndexRoute: appPricingIndexRoute,
  appPrivacyPolicyIndexRoute: appPrivacyPolicyIndexRoute,
  appCheckoutCancelIndexRoute: appCheckoutCancelIndexRoute,
  appCheckoutSuccessIndexRoute: appCheckoutSuccessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
