// This file was automatically generated by generate-env-types.mjs based on .env.

export type EnvironmentVariables = {
  VITE_NODE_ENV: string
  VITE_API_URL: string
  VITE_FRONTEND_URL: string
  VITE_PAYMENT_PUBLIC_KEY: string
  VITE_CONTACT_EMAIL: string
  VITE_SENTRY_DSN: string
}

export const ENV_NAMES = [
  'VITE_NODE_ENV',
  'VITE_API_URL',
  'VITE_FRONTEND_URL',
  'VITE_PAYMENT_PUBLIC_KEY',
  'VITE_CONTACT_EMAIL',
  'VITE_SENTRY_DSN',
] as const

