// This file was automatically generated by generate-env-types.mjs based on .env.

export type EnvironmentVariables = {
  NODE_ENV: string
  PORT: string
  OPENAI_API_KEY: string
  FRONTEND_URL: string
  JWT_SECRET: string
  JWT_REFRESH_SECRET: string
  DATABASE_URL: string
  DIRECT_URL: string
  RESEND_API_KEY: string
  EMAIL_SENDER: string
  STRIPE_SECRET_KEY: string
  STRIPE_WEBHOOK_SECRET: string
  CRON_SECRET_KEY: string
}

export const ENV_NAMES = [
  'NODE_ENV',
  'PORT',
  'OPENAI_API_KEY',
  'FRONTEND_URL',
  'JWT_SECRET',
  'JWT_REFRESH_SECRET',
  'DATABASE_URL',
  'DIRECT_URL',
  'RESEND_API_KEY',
  'EMAIL_SENDER',
  'STRIPE_SECRET_KEY',
  'STRIPE_WEBHOOK_SECRET',
  'CRON_SECRET_KEY'
] as const
